spring:
  application:
    name: unispot-api
    
  # Enable Java 21 Virtual Threads (Project Loom)
  threads:
    virtual:
      enabled: true
      
  datasource:
    # url: jdbc:postgresql://
    url: jdbc:postgresql://localhost:5432/practice
    username: postgres
    password: 
    
  jpa:
    hibernate:
      ddl-auto: create-drop # validate or Flyway in actual production
    show-sql: true
    properties:
      hibernate:
        "[format_sql]": true
  data:
    web:
      pageable:
        max-page-size: 100 #so put ceiling on client request

# Custom properties for JWT and Cloudinary
unispot:
  security:
    jwt:
      secret: 
      #must be 32 bytes, here raw text hence 32 char
      expiration: 900000 # 15 minutes in ms
      refresh-expiration: 604800000 # 7 days in ms